Add queries and inserts according to the reqirements
martinkarugaba/vet-clinic-database pull request #2
Opened 2023-07-18 20:25 UTC by martinkarugaba

# :recycle: Changes made
## No. 1
- [ ] Added column species of type string to animals table. Modiied schema.sql file. 
- [ ] Added more records to animals table
### Inside a transaction, updated the animals table by setting the species column to unspecified

![1](https://github.com/martinkarugaba/vet-clinic-database/assets/55017675/c5a398b2-88b3-4395-be4b-8b56b253d16d)

## Inside a transaction:
### Set the species column to digimon for all animals that have a name ending in mon.

![3](https://github.com/martinkarugaba/vet-clinic-database/assets/55017675/b4ccb8f6-f8a8-4000-94e0-4f9eca99b9e0)

### Set the species column to pokemon for all animals that don't have species already set.

![4](https://github.com/martinkarugaba/vet-clinic-database/assets/55017675/81f8b2f1-df1b-48cd-aebc-80b417c2a148)

### Commited the transaction and verify that changes persist after commit.

![5](https://github.com/martinkarugaba/vet-clinic-database/assets/55017675/db8a1226-154f-49bc-956d-98ce34117505)

## Inside a transaction
### Deleted all records in the animals table, then roll back the transaction. Verifyed if all records in the animals table still exists after the rollback.

![6](https://github.com/martinkarugaba/vet-clinic-database/assets/55017675/da630e67-21b6-4491-8e84-fe8a74f84258)

## Inside a transaction:
### Deleted all animals born after Jan 1st, 2022 and created a savepoint for the transaction.
![9](https://github.com/martinkarugaba/vet-clinic-database/assets/55017675/d86062ef-face-464f-9383-0edf03580361)

### Updated all animals' weight to be their weight multiplied by -1.

![10](https://github.com/martinkarugaba/vet-clinic-database/assets/55017675/aa341e1d-1767-4e68-9398-eddce40d9ab1)

### Rolledback to the savepoint

![11](https://github.com/martinkarugaba/vet-clinic-database/assets/55017675/72e112f3-7e8f-483c-ad33-097ab5bef454)

### Update all animals' weights that are negative to be their weight multiplied by -1.

![12](https://github.com/martinkarugaba/vet-clinic-database/assets/55017675/fababb4a-06bf-4035-bcb5-a4cdfd47cf61)

### Commited transaction

![13](https://github.com/martinkarugaba/vet-clinic-database/assets/55017675/1de5ae33-0f74-4fe1-83d8-3522bcbe078b)

## No. 3

### Wrote queries to answer the following questions:
### How many animals are there?

![14](https://github.com/martinkarugaba/vet-clinic-database/assets/55017675/c1880fe4-be46-48df-8b7d-2b96b16af887)

### How many animals have never tried to escape?

![15](https://github.com/martinkarugaba/vet-clinic-database/assets/55017675/6f440b45-fad1-4d8b-b614-3b01b08436d5)

### What is the average weight of animals?

![16](https://github.com/martinkarugaba/vet-clinic-database/assets/55017675/13d2c930-8208-4eda-8f34-4e3232fed2ed)

### Who escapes the most, neutered or not neutered animals?

![17](https://github.com/martinkarugaba/vet-clinic-database/assets/55017675/08336ad9-a393-4cce-bad7-81bff68b2c4e)

### What is the minimum and maximum weight of each type of animal?

![18](https://github.com/martinkarugaba/vet-clinic-database/assets/55017675/419aaeb5-f666-4bcb-b728-6c5e0b865b79)

### What is the average number of escape attempts per animal type of those born between 1990 and 2000?

![19](https://github.com/martinkarugaba/vet-clinic-database/assets/55017675/230d2bae-ac21-4e76-adb3-f97d40a5cd86)

2023-07-18 20:48 UTC, abdulhamiid requested changes
# Status: Required Changes :recycle:
Hi @martinkarugaba 👋, 
![](https://media.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif)
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there! :running_man: :runner: 
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights 🌟

- ✔️ Descriptions are very descriptive
- ✔️ Use database transactions.
- ✔️ Modify and delete data in SQL.
- ✔️ Prepare complex queries that answer analytical questions.

## Required Changes ♻️
_Please kindly check the comments under the review._

## Optional suggestions 🤷‍♂️
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

## Important Notes 📝
- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-18 20:48 UTC, abdulhamiid commented on README.md
> -
Please fix the links in your Readme for a professional readme

- Tech stack  section
  - The `PostgreSQL` does not navigate to a correct URL 🤓
- License
  - The license link is broken, kindly fix that 👍

2023-07-18 20:48 UTC, abdulhamiid commented on schema.sql
>  );
According to the [project requirements](https://github.com/microverseinc/curriculum-databases/blob/main/db-structure/vet_clinic_query_update_tables.md), kindly add the SQL commands used to add a column `species` of type `string` to your `animals` table.  🤗

2023-07-19 09:10 UTC, DeliceLydia approved these changes
## Hi @martinkarugaba, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
# Congratulations! 🎉 

## Highlights
- Addressed change requested



### Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-19 10:40 UTC, merged

2023-10-24 08:06 UTC, shahadat3669 reviewed
Hi @martinkarugaba, 

Your project is complete!  There is nothing else to say other than it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media2.giphy.com/media/xT0xezQGU5xCDJuCPe/giphy.gif"/>

## Highlights
✅ Animal table is updated
✅ Successful queries and transactions
✅ Screenshots are added
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

## Have any doubt ❓

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

<table  width="100%" align="center">
  <tr>
    <td colspan="4" align="center">
      <strong>Contact me: Shahadat Hossain</strong>
    </td>
  </tr>
  <tr>
    <td align="center">
      <a href="https://github.com/shahadata3669">
        <img src="https://img.shields.io/badge/github-%23121011.svg?style=for-the-badge&logo=github&logoColor=white" alt="GitHub">
      </a>
    </td>
    <td align="center">
      <a href="https://www.linkedin.com/in/shahadat-cseng/">
        <img src="https://img.shields.io/badge/linkedin-%230077B5.svg?style=for-the-badge&logo=linkedin&logoColor=white" alt="LinkedIn">
      </a>
    </td>
    <td align="center">
      <a href="https://app.slack.com/client/T47CT8XPG/D05GT4E4WAY/rimeto_profile/U04426SD71V">
        <img src="https://img.shields.io/badge/Slack-4A154B?style=for-the-badge&logo=slack&logoColor=white" alt="Slack">
      </a>
    </td>
    <td align="center">
      <a href="mailto:shahadat3669@gmail.com?subject=Microverse%20Code%20Review">
        <img src="https://img.shields.io/badge/Gmail-D14836?style=for-the-badge&logo=gmail&logoColor=white" alt="Email">
      </a>
    </td>
  </tr>
</table>

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._